### ISSUE TITLE
The effect is not ideal

### ISSUE THREAD

**Issue by air2583** [BrauerAlexej/Enhancing_actuarial_non-life_pricing_models_via_transformers_Public#1]
Dear author, thank you very much for selflessly sharing the code. At the same time, I think the research is very valuable, as it compares the effects of various models very well and is easy to understand. But due to my insufficient ability, I am unable to perfectly reproduce your results.The loss of the network model is 25%, but the loss of the linear model is 24%, and the test loss is even lower. My professor hopes that I can reproduce your results, which is very distressing for me. I hope you can give me some suggestions and look forward to your reply.

<img width="728" alt="result" src="https://github.com/user-attachments/assets/8d889936-33d9-4531-90ee-c965be93c3ab">

**Comment by BrauerAlexej** [comment]
Hi, and thank you for your comment! 😊

Since your results are based on the "vanilla" FNNs, CANNs, and LocalGLMnets, I'm happy to direct you to the respective papers mentioned in the notebook or paper: https://doi.org/10.1007/s13385-024-00388-2.

I especially recommend reviewing the steps in the book by M. V. Wüthrich and M. Merz, Statistical Foundations of Actuarial Learning and its Applications.

Here are my results from the notebook:
![image](https://github.com/user-attachments/assets/c51df6a2-f152-4e07-b0ca-0be12dd4fa41)
And the corresponding results in the book (see GLM3 / FNN_OHE / LocalGLMnet):
![image](https://github.com/user-attachments/assets/fa2833a8-49f2-4daa-bd14-0b9fea803441)

Tips and Tricks:

- Usually, issues arise in data preparation, so I recommend carefully reading the notebook's chapter on data preparation. Ensure that your results for the GLMs (e.g., GLM_3) are exactly the same as those in the book or my notebook.
- Next, verify that your environment has the same package versions as those used in the original code. Differences here can lead to discrepancies in the results.
- You mentioned the average results above. Did you run the models 15 times and average the outcomes, or did you present results from a single random run? Averaging multiple runs is important for consistent comparisons.

I hope these suggestions help! Good luck with your work 👍

**Comment by air2583** [comment]
Thank you very much for your serious reply. You are the most enthusiastic and kind author I have ever met. Your suggestions are very valuable, and I will try them seriously until I can achieve the desired results. I have a small request, could you please compress your 'Data' folder and send it to me? I hope to reduce the impact of other factors.
This is my email number: sgq0919@outlook.com
I hope it won't disturb you. Wishing you a happy life

**Comment by air2583** [comment]
Thank you very much for your serious reply. You are the most enthusiastic and kind author I have ever met. Your suggestions are very valuable, and I will try them seriously until I can achieve the desired results. I have a small request, could you please compress your 'Data' folder and send it to me? I hope to reduce the impact of other factors.
This is my email number: sgq0919@outlook.com
I hope it won't disturb you. Wishing you a happy life！ @BrauerAlexej
